package LibraryApp;


/**
* LibraryApp/Library.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Library.idl
* Friday, March 8, 2019 7:16:00 o'clock PM EST
*/

public interface Library extends LibraryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Library
