package LibraryApp;


import java.net.UnknownHostException;

/**
* LibraryApp/LibraryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Library.idl
* Friday, March 8, 2019 7:16:00 o'clock PM EST
*/

public interface LibraryOperations 
{
  String addItem (String managerID, String itemID, String itemName, int quantity);
  String removeItem (String managerID, String itemID, int quantity, boolean completeRemove);
  String listItemAvailability (String managerID);
  String borrowItem (String userID, String itemID, int numberOfDays) throws UnknownHostException;
  String findItem (String userID, String itemName) throws UnknownHostException;
  String returnItem (String userID, String itemID);
  String verify (String ID);
  boolean load_server (String server_name);
  String addToWait (String parm, String itemID, String userID);
  String exchangeItem (String userID, String newItemID, String oldItemID);
  void shutdown ();
} // interface LibraryOperations
