package LibraryApp;


/**
* LibraryApp/LibraryHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Library.idl
* Friday, March 8, 2019 7:16:00 o'clock PM EST
*/

abstract public class LibraryHelper
{
  private static String  _id = "IDL:LibraryApp/Library:1.0";

  public static void insert (org.omg.CORBA.Any a, LibraryApp.Library that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static LibraryApp.Library extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (LibraryApp.LibraryHelper.id (), "Library");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static LibraryApp.Library read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_LibraryStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, LibraryApp.Library value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static LibraryApp.Library narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LibraryApp.Library)
      return (LibraryApp.Library)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      LibraryApp._LibraryStub stub = new LibraryApp._LibraryStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static LibraryApp.Library unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LibraryApp.Library)
      return (LibraryApp.Library)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      LibraryApp._LibraryStub stub = new LibraryApp._LibraryStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
